[29기 이동훈] modeling
wecode-bootcamp-korea/29-2nd-NOT-FOUND-404-backend pull request #1
Opened 2022-02-15 09:11 UTC by DongKey777

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 데이터베이스 모델링

<br />

2022-02-15 09:52 UTC, lordmyshepherd requested changes

2022-02-15 09:52 UTC, lordmyshepherd commented on products/models.py
> +# Create your models here.
주석은 지워주세요~

2022-02-15 09:52 UTC, lordmyshepherd commented on products/models.py
> +
class와 class 사이는 한칸이 되도록 수정해주세요-!

2022-02-15 09:52 UTC, lordmyshepherd commented on reviews/models.py
> +    parent        = models.ForeignKey('self', on_delete=models.CASCADE)
parent 보다는 `parent_review`로 이름을 정하는게 더 명확할 것 같습니다.

```suggestion
    parent_review = models.ForeignKey('self', on_delete=models.CASCADE)
```

2022-02-15 09:52 UTC, lordmyshepherd commented on users/models.py
> +    kakao_id     = models.EmailField(max_length=100, null=True)
`kakao_id`는 int 값으로 받게 됩니다.

```suggestion
    kakao_id = models.IntegerField(max_length=100, null=True)
```

2022-02-15 09:52 UTC, lordmyshepherd commented on communities/models.py
> +    parent = models.ForeignKey('self', on_delete=models.CASCADE),
커뮤니티에는 self join이 필요없지 않나요??

2022-02-15 09:58 UTC, DongKey777 commented on communities/models.py
> +    parent = models.ForeignKey('self', on_delete=models.CASCADE),
커뮤니티도 대댓글이 있어서 자기참조를 넣어줬습니다 !

2022-02-15 09:59 UTC, DongKey777 commented
병민님 ! 말씀해주신 부분들 확인하고 수정해서 다시 푸쉬했습니다 !

2022-02-15 11:48 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-02-15 11:48 UTC, lordmyshepherd commented
리베이스해서 올려주세요~!

2022-02-16 01:27 UTC, DongKey777 commented
병민님 리베이스해서 푸쉬했습니다 ~ 👍🏻

2022-02-16 01:47 UTC, lordmyshepherd commented
리베이스하는 과정에서 vscode 관련된 불필요한 파일들이 PR에 포함되었네요!
삭제하고 다시 PUSH 해주세요~
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/53214510/154180594-d8025432-9fee-43dc-babc-25824fabd7c3.png">

2022-02-16 01:53 UTC, DongKey777 commented
.idea 삭제 및 리베이스하여 푸쉬올렸습니다 ~~!

2022-02-16 02:53 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-02-16 02:54 UTC, merged