[29기 김지연] 커뮤니티 view 구현
wecode-bootcamp-korea/29-2nd-NOT-FOUND-404-backend pull request #17
Opened 2022-02-23 01:37 UTC by jiyeon-kim-ds

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 커뮤니티의 CRUD 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 커뮤니티 CRUD 기능 구현
- 커뮤니티에 게시글을 쓰거나 게시글에 댓글을 작성하는 기능 구현,
- 커뮤니티의 게시글을 수정하고 삭제하는 기능 구현
- 커뮤니티의 게시글 조회 기능 구현
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 모델링 시 자기 참조라는게 있다는 것을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항

- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-23 03:18 UTC, lordmyshepherd requested changes

2022-02-23 03:18 UTC, lordmyshepherd commented on communities/views.py
> +        return JsonResponse({'message':'success'}, status=201)
피드백 communities, reviews 분리

```suggestion
class CommunityView
    def post(self, request):
        # community = 게시글  POST :8000/community
        data = json.loads(request.body)

        Community.objects.create(
            user_id = request.user,
            content = data['content'],
            product_id = data['product_id']
        )
        
        return JsonResponse({'message':'success'}, status=201)
```
```python
class CommunityReviewView
    def post(self, request, commnity_id):
        # community = 게시글  POST :8000/community/1/reviews
        data = json.loads(request.body)

        Community.objects.create(
            user_id = request.user,
            content = data['content'],
            product_id = data['product_id']
            parent_id = community_id
        )
        
        return JsonResponse({'message':'success'}, status=201)

```

2022-02-23 03:18 UTC, lordmyshepherd commented on communities/views.py
> +            return JsonResponse({'message': 'No post available'}, status=400)
```suggestion
    def delete(self, request, community_id):
            Community.objects.filter(id=post_id, user_id=request.user).delete()
            return JsonResponse({'message': 'No content'}, status=204)
```

2022-02-23 03:18 UTC, lordmyshepherd commented on communities/views.py
> +    def put(self, request, post_id):
업데이트 방법 patch, put 차이점

2022-02-23 03:18 UTC, lordmyshepherd commented on communities/views.py
> +    def put(self, request, post_id):
```suggestion
    def put(self, request, community):
```

2022-02-24 05:38 UTC, bigfanoftim requested changes
전체 코드 한 번 훑어보시고 리뷰 적용 해주세요!
그리고 Conflict 해결까지~

2022-02-24 05:38 UTC, bigfanoftim commented on communities/views.py
> +            user_id          = request.user,
동작하는데는 문제가 없더라도 좀 더 명확하게 적어주시는게 좋을 것 같아요!
```suggestion
            user          = request.user,
```

2022-02-24 05:38 UTC, bigfanoftim commented on communities/views.py
> +        Community.objects.filter(id=community_id, user_id=request.user).delete()
```suggestion
        Community.objects.filter(id=community_id, user=request.user).delete()
```

2022-02-24 08:45 UTC, bigfanoftim approved these changes

2022-02-24 08:45 UTC, merged