[29기 김지연] 상품 상세페이지 상품 정보 API
wecode-bootcamp-korea/29-2nd-NOT-FOUND-404-backend pull request #6
Opened 2022-02-18 01:51 UTC by jiyeon-kim-ds

convert markdown to html

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 상품 상세 페이지에 **상품 관련 정보**를 반환하는 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 상품 상세 정보 반환
- path parameter로 `product_id`를 받아 해당 상품 정보를 반환한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- `tablename_set.all()`을 이용해 reverse relation인 데이터를 불러오는 것을 알게 되었습니다.
<br />

## :: 기타 질문 및 특이 사항

2022-02-21 09:41 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-23 03:04 UTC, lordmyshepherd requested changes

2022-02-23 03:04 UTC, lordmyshepherd commented on products/views.py
> +            product = Product.objects.select_related('creator','subcategory').get(id=product_id)
```suggestion
            product = Product.objects.select_related('creator','subcategory').get(id=product_id, status_id = ProductStatus.OPEN.value)
```

2022-02-24 05:29 UTC, jiyeon-kim-ds commented
병민님 수정사항 반영하여 푸쉬했습니다~

2022-02-24 05:32 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-24 05:32 UTC, merged